name: release

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  release:
    name: Release *.x Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '23.11.0'

      - name: Install Dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMVER_RELEASE }}
        run: npx semantic-release
